type bool := {
};

type nat := {
	//arithmetic operators
	+: (nat, nat) -> nat;
	-: (nat, nat) -> nat;
	*: (nat, nat) -> nat;
	
	//logical operators
	<=: (nat, nat) -> bool;
};

type string := {
	+: (string, string) -> string;
};

type unit := {
};

type unsigned := {
	//arithmetic operators
	+: (unsigned, unsigned) -> unsigned;
	-: (unsigned, unsigned) -> unsigned;
	
	//logical operators
	<=: (unsigned, unsigned) -> bool;
};

let print: any -> unit := extern "print";
